# Generated by Django 4.0.4 on 2022-05-21 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fscohort', '0003_student_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['number'], 'verbose_name': 'Öğrenci', 'verbose_name_plural': 'Öğrenciler'},
        ),
    ]
